// <auto-generated />
using System;
using CaloriesSmartCalulator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CaloriesSmartCalulator.Data.Migrations
{
    [DbContext(typeof(CaloriesCalulatorDBContext))]
    [Migration("20210909125603_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CaloriesSmartCalulator.Data.Entities.CaloriesCalculationTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FailedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FinishedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InProgressOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CaloriesCalculationTasks");
                });

            modelBuilder.Entity("CaloriesSmartCalulator.Data.Entities.CaloriesCalculationTaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<Guid>("CaloriesCalculationTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FailedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FinishedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Product")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaloriesCalculationTaskId");

                    b.ToTable("CaloriesCalculationTaskItems");
                });

            modelBuilder.Entity("CaloriesSmartCalulator.Data.Entities.CaloriesCalculationTaskItem", b =>
                {
                    b.HasOne("CaloriesSmartCalulator.Data.Entities.CaloriesCalculationTask", "CaloriesCalculationTask")
                        .WithMany("CaloriesCalculationTaskItems")
                        .HasForeignKey("CaloriesCalculationTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaloriesCalculationTask");
                });

            modelBuilder.Entity("CaloriesSmartCalulator.Data.Entities.CaloriesCalculationTask", b =>
                {
                    b.Navigation("CaloriesCalculationTaskItems");
                });
#pragma warning restore 612, 618
        }
    }
}
